### ISSUE TITLE
Server error 500 while editing field type after Craft CMS update

### ISSUE THREAD

**Issue by ammannbe** [percipioglobal/craft-colour-swatches#74] opened 2021-11-24 12:38 UTC
Since the last Craft Update, the color swatches do not show anymore in the entries edit page.
Also if we try to edit the field itself, we receive a server error 500.

This is the stack trace in the logfile:

```
2021-11-24 04:32:31 [-][1][23d61f85eb750d5f3a69454d390e777f][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: Colour config in /var/www/vhosts/example.com/httpdocs/vendor/percipioglobal/craft-colour-swatches/src/fields/ColourSwatches.php:130
Stack trace:
#0 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 130)
#1 /var/www/vhosts/example.com/httpdocs/vendor/percipioglobal/craft-colour-swatches/src/fields/ColourSwatches.php(130): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 130, Array)
#2 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1511): percipioglobal\colourswatches\fields\ColourSwatches->getSettingsHtml()
#3 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(percipioglobal\colourswatches\fields\ColourSwatches), 'getSettingsHtml', Array, 'method', false, false)
#4 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/7b/7b6375ce555568f3bb18a41429ce31ceb6852016678e2cc0013cbf6ea539c9f5.php(503): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(percipioglobal\colourswatches\fields\ColourSwatches), 'getSettingsHtml', Array, 'method')
#5 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_b10230a18b4463020751decf97dff9700fc902f663c0608c5af1db41c2aec2b8->doDisplay(Array, Array)
#6 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#8 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#9 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#10 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_components/fie...', Array)
#11 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/fields/Matrix.php(501): craft\web\View->renderTemplate('_components/fie...', Array)
#12 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1511): craft\fields\Matrix->getSettingsHtml()
#13 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method', false, false)
#14 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/5f/5f656aaa046e0e31c30114760f2ef5f18769888fdd1abc946f0a908fbb9927e0.php(506): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method')
#15 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_80757d8bda9fb2aa8991de63518f2769c5320e95d64e6f70ca4af557cc355410->doDisplay(Array, Array)
#16 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#18 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#19 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#20 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('super-table/set...', Array)
#21 /var/www/vhosts/example.com/httpdocs/vendor/verbb/super-table/src/fields/SuperTableField.php(519): craft\web\View->renderTemplate('super-table/set...', Array)
#22 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1511): verbb\supertable\fields\SuperTableField->getSettingsHtml()
#23 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\supertable\fields\SuperTableField), 'getSettingsHtml', Array, 'method', false, false)
#24 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/fa/fa214567b8af79577ec3f74eabae3e0360fdb5ab5e72f0ad0e06e6b8dd5cd6a6.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\supertable\fields\SuperTableField), 'getSettingsHtml', Array, 'method')
#25 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_293aa696c9b7b0ce0b9a07792d6d1345c4f695435f63aba1b58dd971d574be90->doDisplay(Array, Array)
#26 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#27 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/e3/e3660af70c63ef630dd988bacec5942ef75cab7ffce45e6a0a6726fab77df9d1.php(256): Twig\Template->display(Array)
#28 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(182): __TwigTemplate_1ddab671a4ef69487b6b47413a1b55d2543ad9c6080e0e96bb97014e2aab8ffb->block_content(Array, Array)
#29 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/c7/c750cb3fa4193d8c2ca17b8eeea771e6b6d0a1490a2b86d2c6c8c37ce6b0940d.php(535): Twig\Template->displayBlock('content', Array, Array)
#30 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(182): __TwigTemplate_094f9043ad0b1bb70248a01d2d49cda00d09d490b05c1eb1bb240f0043257065->block_main(Array, Array)
#31 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/c7/c750cb3fa4193d8c2ca17b8eeea771e6b6d0a1490a2b86d2c6c8c37ce6b0940d.php(346): Twig\Template->displayBlock('main', Array, Array)
#32 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(182): __TwigTemplate_094f9043ad0b1bb70248a01d2d49cda00d09d490b05c1eb1bb240f0043257065->block_body(Array, Array)
#33 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/09/09ba9be8d35fab53e98a73702308b3ac89adb60542f99f7d6f339d00813bd41a.php(96): Twig\Template->displayBlock('body', Array, Array)
#34 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0325e92cd9af442875a635b4bdd46511860fe7ad77cc2ab9d28b8baf61eddbad->doDisplay(Array, Array)
#35 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#36 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/51/517b24062aaa9dc9091445d3854f3378c8519c44c7a104d4e2ecf63adb3e47fc.php(56): Twig\Template->display(Array, Array)
#37 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_d144fd09f561c649abb4770f57eb2f09b7068f6e55f2d468c43ded6da044e048->doDisplay(Array, Array)
#38 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#39 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/c7/c750cb3fa4193d8c2ca17b8eeea771e6b6d0a1490a2b86d2c6c8c37ce6b0940d.php(165): Twig\Template->display(Array, Array)
#40 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_094f9043ad0b1bb70248a01d2d49cda00d09d490b05c1eb1bb240f0043257065->doDisplay(Array, Array)
#41 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#42 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/e3/e3660af70c63ef630dd988bacec5942ef75cab7ffce45e6a0a6726fab77df9d1.php(114): Twig\Template->display(Array, Array)
#43 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_1ddab671a4ef69487b6b47413a1b55d2543ad9c6080e0e96bb97014e2aab8ffb->doDisplay(Array, Array)
#44 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#45 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#46 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#47 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#48 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('settings/fields...', Array)
#49 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('settings/fields...', Array)
#50 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate('settings/fields...', Array, 'cp')
#51 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/controllers/FieldsController.php(258): craft\web\Controller->renderTemplate('settings/fields...', Array)
#52 [internal function]: craft\controllers\FieldsController->actionEditField(75, Object(verbb\supertable\fields\SuperTableField), '9')
#53 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#54 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#55 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('edit-field', Array)
#56 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('fields/edit-fie...', Array)
#57 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('fields/edit-fie...', Array)
#58 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#59 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#60 /var/www/vhosts/example.com/httpdocs/web/index.php(26): yii\base\Application->run()
#61 {main}
2021-11-24 04:32:31 [-][1][23d61f85eb750d5f3a69454d390e777f][info][application] $_GET = [
    'p' => 'admin/settings/fields/edit/75'
]
```

Not sure if it is a problem with craft itself or not...
Thanks for your help!

Cheers

**Comment by michtio** [comment] 2021-11-24 12:42
Hey @ammannbe 

First thing I Notice is:

```
2021-11-24 04:32:31 [-][1][23d61f85eb750d5f3a69454d390e777f][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: Colour config in /var/www/vhosts/example.com/httpdocs/vendor/percipioglobal/craft-colour-swatches/src/fields/ColourSwatches.php:130
Stack trace:
```

Could you maybe also share the contents of your colour-swatches.php file, as I have a feeling the issue might lie in there.

Can you also define "latest Craft", is that `3.7.22` ? Thank you!

**Comment by ammannbe** [comment] 2021-11-24 12:44
Hi @michtio 

Thanks for the fast response.

This is the content of my config file:
```
<?php
return [
    'colors' => [
        [
            'label'   => 'reset',
            'color'   => '#fff',
            'default' => true,
        ],
        [
            'label'   => 'dark',
            'color'   => '#4C4E4F',
            'default' => false,
        ],
        [
            'label'   => 'muted',
            'color'   => '#EBEBDC',
            'default' => false,
        ],
    ]
];
```

Yes, my current version is `Craft CMS 3.7.22`

**Comment by michtio** [comment] 2021-11-24 12:49
Thank you @ammannbe I'll make sure this gets tested ASAP, and will report back or push a fix if necessary or contact our friends at pixel and tonic if it seems to be on their side.

**Comment by domstubbs** [comment] 2021-11-24 17:22
Coincidentally I’ve added this plugin to a project this afternoon and I’m seeing the same error.

I’ve created a field with the ‘use config options’ setting enabled. This has result in the following project config output:

````
settings:
  options: ''
  palette: 'Colour config'
  useConfigFile: '1'
````

Given that the plugin seems to be looking for a `Colour config` array key in colour-swatches.php it seems as if the field settings are assigning a default palette and things are failing when that palette isn’t present in the config file.

I’ve been able to verify this by adding a palette named ‘Colour config’ to my config, as that does then render in the CP without errors.

It seems like a palette name might be being assigned to the field when it shouldn’t be? If this is a Craft issue then perhaps there’s a bug where disabled/hidden settings are being processed when they shouldn’t be?

**Comment by ammannbe** [comment] 2021-12-02 10:43
I can confirm that, if I add a empty palette, the server error disappears.

```
<?php
return [
    'colors' => [
        ...
    ],
    // Add these lines
    'palettes' => [
        'Colour config' => [],
    ]
];
```

**Comment by cookie10codes** [comment] 2021-12-06 15:32
hi @ammannbe 👋🏼 

Is it possible to send over your project config, colour-swatches.php and composer.json? You can make a Wetransfer and mail it over to stefanie@percipio.london if you like. I can't reproduce with my setup.

Some additional questions:
1. When was the first install approx of the plugin on your project?
2. You encountered the same problem on a new setup of was the other project an older Craft setup?

Thanks for being patient and helping us out to dig out the issue

**Comment by michtio** [comment] 2021-12-09 18:30
@ammannbe @domstubbs 

There is a release candidate ready which fixes quite some issues with colour swatches, there is a check if a certain index doesn't exist in the config file in place, which might solve the issue.

You can find the RC here:

```
https://github.com/percipioglobal/craft-colour-swatches/releases/tag/1.5.0-RC.1
```

If you update your composer.json to 1.5.0-RC.1 for colour swatches it might fix the issue, let us know if it does, probably an official release of 1.5.0 goes out tomorrow tho :)

**Comment by ammannbe** [comment] 2021-12-13 08:04
@michtio 

Thank you very much for the bugfix.
I've tested the release 1.5.0 and it works as expected :).

Therefore I'll close this issue.

**Comment by michtio** [comment] 2021-12-13 09:03
Great happy it works @ammannbe !

**Comment by ammannbe** [comment] 2021-12-13 13:04
Sorry to bother you again.
After the update we noticed, that we couldn't save the entries anymore.

This is the error in the logfile:

```
2021-12-13 04:44:50 [-][1][8c079862adc958550aaca723f0420058][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index:  in /var/www/vhosts/example.ch/httpdocs/vendor/percipioglobal/craft-colour-swatches/src/fields/ColourSwatches.php:117
Stack trace:
#0 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 117)
#1 /var/www/vhosts/example.ch/httpdocs/vendor/percipioglobal/craft-colour-swatches/src/fields/ColourSwatches.php(117): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 117, Array)
#2 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/base/Element.php(2120): percipioglobal\colourswatches\fields\ColourSwatches->serializeValue(Object(percipioglobal\colourswatches\models\ColourSwatches), Object(craft\elements\MatrixBlock))
#3 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldContentSize('blockColor', NULL, Object(yii\validators\InlineValidator), Object(percipioglobal\colourswatches\models\ColourSwatches))
#4 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\MatrixBlock), 'blockColor')
#5 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(craft\elements\MatrixBlock), Array)
#6 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/fields/Matrix.php(801): yii\base\Model->validate()
#7 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/base/Element.php(2093): craft\fields\Matrix->validateBlocks(Object(verbb\supertable\elements\SuperTableBlockElement), NULL)
#8 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldAttribute('field:blockElem...', Array, Object(yii\validators\InlineValidator), Object(craft\elements\db\MatrixBlockQuery))
#9 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(verbb\supertable\elements\SuperTableBlockElement), 'field:blockElem...')
#10 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(verbb\supertable\elements\SuperTableBlockElement), Array)
#11 /var/www/vhosts/example.ch/httpdocs/vendor/verbb/super-table/src/fields/SuperTableField.php(833): yii\base\Model->validate()
#12 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/base/Element.php(2093): verbb\supertable\fields\SuperTableField->validateBlocks(Object(craft\elements\Entry), NULL)
#13 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldAttribute('field:blocks', Array, Object(yii\validators\InlineValidator), Object(verbb\supertable\elements\db\SuperTableBlockQuery))
#14 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'field:blocks')
#15 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#16 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/services/Elements.php(2534): yii\base\Model->validate()
#17 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/services/Elements.php(783): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, NULL)
#18 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/controllers/EntriesController.php(403): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#19 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#20 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#22 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('save-entry', Array)
#23 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('entries/save-en...', Array)
#24 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('entries/save-en...', Array)
#25 /var/www/vhosts/example.ch/httpdocs/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#26 /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /var/www/vhosts/example.ch/httpdocs/web/index.php(26): yii\base\Application->run()
#28 {main}
2021-12-13 04:44:49 [-][1][8c079862adc958550aaca723f0420058][info][application] $_GET = [
    'p' => 'admin/entries/landingpages/891-landingpage'
]
```

I think the problem is that we never worked with palettes and therefore this line throws of course an undefined index:
https://github.com/percipioglobal/craft-colour-swatches/blob/2b834f8693e536048f0329f83845688bef28434a/src/fields/ColourSwatches.php#L117

But it should solve the problem if you just change the line from
`if(Plugin::$plugin->settings->palettes[$this->palette]){`
to
`if(Plugin::$plugin->settings->palettes[$this->palette] ?? false){`

I've just made a pull request, could you merge it?

Thanks!

**Comment by michtio** [comment] 2021-12-13 13:09
Thank you @ammannbe , this has been merged and release has been pushed up.

**Closed by michtio** 2021-12-13 13:09 UTC
Labels: bug

**Comment by ammannbe** [comment] 2021-12-13 13:30
Wow, thank you very much.
Could you update at least https://packagist.org/packages/percipioglobal/craft-colour-swatches#1.5.0 ?

And if possible also the Craft Plugin Store?

**Comment by michtio** [comment] 2021-12-13 13:52
All done @ammannbe , I forgot to update the composer.json version number 😬  so 1.5.0.3 it is 😅

**Comment by ammannbe** [comment] 2021-12-13 14:20
Perfect :D
Thank you!
